db:
  build: ./docker/db
  name: db
  ports:
   - "5432:5432"
  volumes:
   - ./docker/db/data:/var/lib/postgresql/data
  env_file:
   - ./docker/db/pgConf.env

web:
  build: ./docker/server
  name: server
  links:
   - db
  ports:
   - '8080:8080'
  volumes:
   - ./build:/lindoria
  command: npm start
  environment:
   - NODE_ENV=staging


